name: Workflow
on:
  push:
    branches: 
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Startup
        run: echo "Starting up linter job"
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
          pipenv install
          pip freeze
      - name: Analysing the code with pylint
        run: | 
          pylint ../movie-addict-api --rcfile .pylintrc --errors-only --verbose
      - name: Shutdown
        run: echo "Linter job finished"
